/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BubbleProgress: typeof import('./src/components/atoms/BubbleProgress.vue')['default']
    Camera: typeof import('./src/components/overlays/Camera.vue')['default']
    Canvas: typeof import('./src/components/overlays/Canvas.vue')['default']
    Countdown: typeof import('./src/components/overlays/Countdown.vue')['default']
    DeviceOrientation: typeof import('./src/components/steppers/DeviceOrientation.vue')['default']
    ExerciseView: typeof import('./src/components/views/ExerciseView.vue')['default']
    FloatingParticles: typeof import('./src/components/atoms/FloatingParticles.vue')['default']
    Initializing: typeof import('./src/components/steppers/Initializing.vue')['default']
    Loader: typeof import('./src/components/overlays/Loader.vue')['default']
    LoaderView: typeof import('./src/components/views/LoaderView.vue')['default']
    Overlay: typeof import('./src/components/atoms/Overlay.vue')['default']
    Phone: typeof import('./src/components/atoms/icons/Phone.vue')['default']
    Pose: typeof import('./src/components/overlays/Pose.vue')['default']
    Progress: typeof import('./src/components/overlays/Progress.vue')['default']
    RepScoreCard: typeof import('./src/components/overlays/RepScoreCard.vue')['default']
    RestView: typeof import('./src/components/views/RestView.vue')['default']
    RestViewWithResults: typeof import('./src/components/views/RestViewWithResults.vue')['default']
    RestViewWithVideo: typeof import('./src/components/views/RestViewWithVideo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SoundCheck: typeof import('./src/components/steppers/SoundCheck.vue')['default']
    TimedScoreCard: typeof import('./src/components/overlays/TimedScoreCard.vue')['default']
    WorkoutVideo: typeof import('./src/components/overlays/WorkoutVideo.vue')['default']
  }
}
