/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BubbleProgress: typeof import('./src/components/atoms/BubbleProgress.vue')['default']
    Camera: typeof import('./src/components/atoms/overlays/Camera.vue')['default']
    Canvas: typeof import('./src/components/atoms/overlays/Canvas.vue')['default']
    Countdown: typeof import('./src/components/atoms/overlays/Countdown.vue')['default']
    ExerciseView: typeof import('./src/components/organisms/ExerciseView.vue')['default']
    Loader: typeof import('./src/components/atoms/overlays/Loader.vue')['default']
    Overlay: typeof import('./src/components/atoms/Overlay.vue')['default']
    Pose: typeof import('./src/components/atoms/overlays/Pose.vue')['default']
    Progress: typeof import('./src/components/atoms/overlays/Progress.vue')['default']
    RepScoreCard: typeof import('./src/components/atoms/overlays/RepScoreCard.vue')['default']
    RestView: typeof import('./src/components/organisms/RestView.vue')['default']
    RestViewWithVideo: typeof import('./src/components/molecules/RestViewWithVideo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TimedScoreCard: typeof import('./src/components/atoms/overlays/TimedScoreCard.vue')['default']
    WorkoutVideo: typeof import('./src/components/atoms/overlays/WorkoutVideo.vue')['default']
  }
}
